export const GET_CURRENT_NETWORK = "GET_CURRENT_NETWORK";
export const INIT_APP = "INIT_APP";
export const CLOSE_MINING_DIALOG = "CLOSE_MINING_DIALOG"
// export const GENERATE_RANDOM_DATA = "GENERATE_RANDOM_DATA";
// export const COMMIT = "COMMIT";