export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_CURRENT_NETWORK = "SET_CURRENT_NETWORK";
export const SET_ETHERSCAN_NETWORK = "SET_ETHERSCAN_NETWORK";
export const SET_WEB3 = "SET_WEB3";
//Contracts
export const SET_CFD = "SET_CFD";
export const SET_UNISWAP = "SET_UNISWAP";
export const SET_UPSIDEDAI = "SET_UPSIDEDAI";
export const SET_UPDAI = "SET_UPDAI";
export const SET_DAI = "SET_DAI";
export const SET_DOWNDAI = "SET_DOWNDAI";
export const SET_UNISWAPUPDAI = "SET_UNISWAPUPDAI";
export const SET_UNISWAPDOWNDAI = "SET_UNISWAPDOWNDAI";
export const SET_UNISWAPFACTORY = "SET_UNISWAPFACTORY";
export const SET_UNISWAPDAI = "SET_UNISWAPDAI"
// User Values
export const SET_DAIBALLANCE = "SET_DAIBALLANCE";
export const SET_ETHBALLANCE = "SET_ETHBALLANCE";
export const SET_MINING_TRANSACTION_OBJECT = "SET_MINING_TRANSACTION_OBJECT";
